### ISSUE TITLE
Deployed functions fails to read runtime config on Node 10

### ISSUE THREAD

**Issue by FredyC** [firebase/firebase-functions#630]
### Related issues

https://github.com/firebase/firebase-functions/issues/433

### [REQUIRED] Version info

**node:** 10.16.0

**firebase-functions:** 3.3.0

**firebase-tools:** 7.15.0

**firebase-admin:** 8.10.0

### [REQUIRED] Test case

I tried to create reproduction in repo https://github.com/FredyC/firebase-functions-repro
Unfortunately, it behaves correctly I did not found any difference from my _broken_ project.

### [REQUIRED] Steps to reproduce

See above

### [REQUIRED] Expected behavior

To have a deployed function that can read a runtime config.

### [REQUIRED] Actual behavior

We have like 15 functions deployed in production and they are running smoothly for several months now. They are all Node 10 functions.

Today, I needed to tweak one function a little, I've deployed it (with `--only` flag) and suddenly that one function is unable to read runtime config, it's always undefined.

In the console log, I've noticed the warning 

> Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail

I assume it's major culprit if this issue, however considering that I have dependencies of the exact same version in a project and in _reproduction_ repo then I don't follow what this warning depends on.

### Were you able to successfully deploy your functions?

Functions do deploy, but fail in runtime when reading `functions.config()`.

**Comment by tilgovi** [comment]
`firebase-admin` will check for `GOOGLE_CLOUD_PROJECT || GCLOUD_PROJECT`. I think `firebase-functions` should probably do the same. Some guidance from GCP about what the most modern option here is would be welcome.

**Comment by the0rem** [comment]
This is pretty frustrating as we had the staging CI deploy and run fine however the deploy to production doesn't have the config data (because it was deployed after the bug was released).

There's also no way to rollback and fortunately we realised (after a couple hours of debugging) that the issue was specific to using the `region()` command which meant we could at least re-deploy our functions in favour of `https` and `firebase` firebase-function declarations.

The fact that this issue wasn't caught by your internal CI systems, as well as the fact that there's no way for the end user to recover and rollback from the issue is embarrassing.

Please rectify this with high priority.

**Comment by FredyC** [comment]
@tilgovi You mean like either of those should be set locally? Why in that case it's working with fresh barebone project? I certainly haven't set any env variable.

@the0rem The workaround to deploy to default (US) region seems to be working indeed, thank you for that at least.

I am honestly surprised this has got several 👍 overnight, I thought it's some issue in my setup.

**Comment by wvanderdeijl** [comment]
We are now unable to deploy any function due to `Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail`

The only env vars we see at runtime are:
`["NODE_ENV","K_SERVICE","FUNCTION_TARGET","NODE_OPTIONS","FUNCTION_SIGNATURE_TYPE","K_REVISION","HOME","DEBIAN_FRONTEND","PWD","PORT","PATH","NO_UPDATE_NOTIFIER"]`

So, there is no FIREBASE_CONFIG nor GCLOUD_PROJECT anymore. Might this be a change in the underlying GCP function infrastructure?

**Comment by FredyC** [comment]
Interesting. I just tried to deploy the minimal reproduction again and suddenly it behaves broken too. The warning is visible in logs as well. Yesterday I deployed several times and it was working. Really strange.

https://europe-west1-test-1a2c7.cloudfunctions.net/helloWorld

Running `firebase functions:config:get` gives me

```json
{
  "hello": {
    "world": "now"
  }
}
```

I hope that reproduction will help with fixing this soon.

**Comment by wvanderdeijl** [comment]
We currently have a number of GCP projects that suffer from this issue (in europe-west1) and another set of projects that do not suffer from this. Seems we're in the middle of some sort of rollout that breaks things

**Comment by mbleigh** [comment]
Hey folks, we see these reports and are investigating. The GCF Node.js environment does not have `GCLOUD_PROJECT` or `FIREBASE_CONFIG` environment variables in the runtime by default, but the Firebase CLI should be inserting them. We'll try to reproduce and go from there.

**Comment by tilgovi** [comment]
So the issue on my end may be that I'm not using the firebase CLI to deploy my functions.

**Comment by FredyC** [comment]
@mbleigh Feel free to use my reproduction repo including that test project, I can transfer it to someone.

**Comment by pavadeli** [comment]
I think something has changed in the directory structure that is deployed to / inside GCF. In our case the code was unable to find the `.runtimeconfig.json` that is automatically packaged with the code. We are currently testing the following workaround which seems to fix it in our environment.

```typescript
// WORKAROUND FOR ISSUE: https://github.com/firebase/firebase-functions/issues/630
import { readFileSync } from 'fs';
import { resolve } from 'path';
try {
    process.env.CLOUD_RUNTIME_CONFIG = process.env.CLOUD_RUNTIME_CONFIG
        || readFileSync(resolve(__dirname, '.runtimeconfig.json'), 'utf8');
} catch (e) {
    console.log('setting CLOUD_RUNTIME_CONFIG failed', e);
}
// END WORKAROUND
```

Note that `.runtimeconfig.json` is in the root of the deployment, so make sure to get the relative path right (in our case, the file that includes the workaround (our `index.ts`) happens to be in the root as well).

Also, the workaround needs to be executed before any function is registered.

**Comment by wvanderdeijl** [comment]
I can see differences in the ENV VARS and working directory on two GCP projects where I deploy the same function:

## project1 (which is working)
```
ENV VARS { 
  DEBIAN_FRONTEND: 'noninteractive'  
  FIREBASE_CONFIG:  
   '{"projectId":"xxx-wilfred","databaseURL":"https://xxx-wilfred.firebaseio.com","storageBucket":"xxx-wilfred.appspot.com","locationId":"europe-west"}'  
  GCLOUD_PROJECT: 'xxx-wilfred'
  FUNCTION_SIGNATURE_TYPE: 'http'  
  FUNCTION_TARGET: 'addEvent'  
  HOME: '/root'  
  K_REVISION: '40'  
  K_SERVICE: 'addEvent'  
  NO_UPDATE_NOTIFIER: 'true'  
  NODE_ENV: 'production'  
  NODE_OPTIONS: '--max-old-space-size=2048'  
  OLDPWD: '/srv'  
  PATH:  
   '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'  
  PORT: '8080'  
  PWD: '/srv/functions'  
  SHLVL: '1'  
  _: '../start-functions-framework'  
}
CURRENT DIR /srv/functions  
__DIRNAME /srv/functions  
FILES '.runtimeconfig.json'  
```

## project2 (missing env vars)
```
@@@ ENV VARS { 
  DEBIAN_FRONTEND: 'noninteractive'  
  FUNCTION_SIGNATURE_TYPE: 'http'  
  FUNCTION_TARGET: 'addEvent'  
  HOME: '/root'  
  K_REVISION: '239'  
  K_SERVICE: 'addEvent'  
  NO_UPDATE_NOTIFIER: 'true'  
  NODE_ENV: 'production'  
  NODE_OPTIONS: '--max-old-space-size=2048'  
  PATH:  
   '/layers/google.nodejs.npm/npm/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  PORT: '8080'  
  PWD: '/srv'  
}  
CURRENT DIR /workspace  
__DIRNAME /workspace  
FILES .runtimeconfig.json
```

This shows that both containers include the `.runtimeconfig.json` that is added by the firebase CLI. But the first one appears to have been started by `../start-functions-framework`, has a number of additional env vars, a different working directory, and more importantly is working.

Could it be that different GCP projects are using different "magic" while doing the functions build and deploy?
